# Suduko Solver

The aim of this code is to accept a 9x9 grid input (i.e. a blank suduko) and return a different grid which corresponds to the answer to the suduko.

## Define a grid

The input grid will take the form of a list of lists. The parent list (of lists) will contain 9 lists, each with 9 elements corresponding to what is in the suduko. E.g. if a box contains the number 5, then the corresponding element in the list of lists will be 5; if the box is blank to begin with, then the corresponding element in the list of lists will be 0.

Below is an empty example grid which can be copied and filled out for convenience: 

In [1]:
grid = [[9,4,0,0,0,0,0,0,0],
         [0,0,0,4,3,7,0,0,0],
         [0,0,0,0,0,0,2,0,0],
         [0,0,0,5,0,6,0,7,0],
         [3,0,8,0,0,0,0,5,0],
         [0,6,0,0,0,4,0,2,0],
         [1,0,5,0,7,0,0,0,0],
         [0,0,0,8,0,0,0,0,9],
         [0,0,4,0,9,0,0,0,1]]am

To call an individual element in this list of lists we use the command:
    
    grid[y][x]

where y corresponds to the row of the grid and x corresponds to the column of the grid. Remember that this a grid with python indexing - the indices start from 0 (i.e. the first row and first column have an index of 0).

If we want to print the grid nicely to the console then we can use the matrix function in numpy.

In [2]:
import numpy as np

In [3]:
g = np.matrix(grid)
print(g)

[[9 4 0 0 0 0 0 0 0]
 [0 0 0 4 3 7 0 0 0]
 [0 0 0 0 0 0 2 0 0]
 [0 0 0 5 0 6 0 7 0]
 [3 0 8 0 0 0 0 5 0]
 [0 6 0 0 0 4 0 2 0]
 [1 0 5 0 7 0 0 0 0]
 [0 0 0 8 0 0 0 0 9]
 [0 0 4 0 9 0 0 0 1]]


In [4]:
grid[0][8]

0

## Solving

We want to be able to determine if a number (n) can go in a certain location. This means testing three conditions:
- is n in the row?
- is n in the column?
- is n in the larger suduko square


#### How to assign a large suduko square to a (y,x) position?

We can create another 3x3 grid in terms of x0 and y0 corresponding to the large squares.

For the rows (x), x0 = 0,1,2
For the columns (y) y0 = 0,1,2

if a position (y,x) has a an x element == 5 (i.e. the 6th position), it lies in the second box, i.e. x0=1.

This x0 value can be calculated for any given x value using `x0 = x//3` 

In [5]:
def possible(y,x,n): # Tests if the number n can go in position (y,x)
    global grid # allows the function to use the grid input from outside the function
    for i in range(9):
        if grid[y][i] == n: # if n is in the same column as (y,x) then the function returns false
            return False
    for i in range(9):
        if grid[i][x] == n: # if n is in the same row as (y,x) then the function returns false
            return False
    # Now to test if the number n is in the same square as the (y,x)
    y0 = y // 3 # define the y element of the large box
    x0 = x // 3 # define the x element of the large box
    for i in range(3):
        for j in range(3):
            if grid[(y0*3) +i][(x0*3)+j] == n: # iterate over the 9 elements (j,i) in the large box containing (y,x)
                return False # return false if the number being tested n is in the large box
    return True # If the number n can be at position (y,x) then the function returns True

In [6]:
possible(0,2,2)

True

In [7]:
0//3

0

## Solving the entire grid

Now that we can determine whether or not it is possible for a number to go in a particular square, we must test every possible blank square.

We must iterate through the y and x values to find a blank square. Then we must test if the numbers 1-9 can go in that square using the `possible` function. If a number n can go there, we assign that (y,x) position as the number n. Then we call the same function again as a recursion in order to find and test the next blank space.

However, if we come across a blank space and we test and find that none of the numbers 1-9 can go there, we must back-track to that first possibility and assign it as blank.

In [8]:
def solve():
    global grid #ensure the outside variable grid runs inside the function
    for y in range(9):
        for x in range(9):
            if grid[y][x] == 0: # iterate across the entire grid searching for blank square
                for n in range(1,10):
                    if possible(y,x,n): # test if numbers 1-9 can go in the blank space
                        grid[y][x] = n # if the number can go here, assign that position (y,x) as that number
                        solve() # call the same function again in a form of recursion
                        grid[y][x] = 0 # back-track - this sets the position as 0, and tests the next n in the n for loop
                # If no blank space can be found, then the suduko must be solved
                return
    print(np.matrix(grid))
    input("more?") # This allows the user to see if there are any other solutions to the blank suduko. 
                   # Ideally, there should be only 1 solution.

In [9]:
solve()

[[9 4 6 1 5 2 3 8 7]
 [2 8 1 4 3 7 6 9 5]
 [7 5 3 9 6 8 2 1 4]
 [4 2 9 5 8 6 1 7 3]
 [3 1 8 7 2 9 4 5 6]
 [5 6 7 3 1 4 9 2 8]
 [1 9 5 6 7 3 8 4 2]
 [6 7 2 8 4 1 5 3 9]
 [8 3 4 2 9 5 7 6 1]]
more?
